---
- hosts: mywebserver
  become: yes
  tasks:
    - name: install java on ubantu node
      apt:  
        name: "{{java_pack_ubutnu_node}}"
        state: present
      when: ansible_os_family=="Debian"
    - name: install java on redhat node
      ansible.builtin.dnf:  
        name: "{{java_pack_redhat_node}}"
        state: present
      when: ansible_os_family=="RedHat"
