---
- hosts: all
  become: yes
  tasks:
    - name: I want to install webserver on ubantu nodes
      apt:
        name: apache2
        state: present
    - name: Iwant to start the webserver
      service: 
        name: apache2
        state: started